# Generated by Django 4.1.6 on 2023-07-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_masteruser_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterUser',
        ),
    ]
