# Generated by Django 4.1.6 on 2023-07-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmodel',
            name='is_draft',
        ),
    ]
