# Generated by Django 4.1.6 on 2023-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notesmodel_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='introductory_text',
            field=models.CharField(default='asd', max_length=350),
            preserve_default=False,
        ),
    ]
