# Generated by Django 4.1.6 on 2023-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notesmodel_introductory_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmodel',
            name='introductory_text',
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='summary',
            field=models.TextField(default='error', max_length=350),
            preserve_default=False,
        ),
    ]
