# Generated by Django 4.1.6 on 2023-07-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notesmodel_introductory_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
